### ISSUE TITLE
Module installs into incorrect path on clean install.

### ISSUE THREAD

**Issue by james481** [ColourboxDevelopment/simplesamlphp-module-redis#4]
When installing a new system from a lock file (empty vendor directory, lock file in place) with `composer install` under some circumstances results in the module not properly installing to the `/vendor/simplesamlphp/simplesamlphp/modules` location, instead will end up in `/modules`. This seems to be the result of composer installing the module package before the base simpleSAMLphp package has been installed.

This is fixed by adding the simpleSAMLphp base module as a dependency in the module `composer.json` to ensure composer installs it first, see #3 .

**Comment by moffe42** [comment]
This is an error in the module installer. This was fixed in version 1.1.4, https://github.com/simplesamlphp/composer-module-installer/releases/tag/v1.1.4.
I will update the composer.json.
