### ISSUE TITLE
Question about config.php

### ISSUE THREAD

**Issue by ghost** [ColourboxDevelopment/simplesamlphp-module-redis#8]
Hello,

Where exactly does this config below go into? should this go into the config.php file? That files already has a $config, please advise.

$config = [
    // Predis client parameters
    'parameters' => 'tcp://localhost:6379',

    // Predis client options
    'options' => null,

    // Key prefix
    'prefix' => 'simpleSAMLphp',

    // Lifitime for all non expiring keys
    'lifetime' => 288000
];

**Comment by ghost** [comment]
ok never mind, it looks like this file is simply placed into the /config directory as a separate redis file.

**Comment by moffe42** [comment]
The configuration option is for the Redis module. The module is used for backend storage of sessions etc. An example is supported in the config-templates directory, https://github.com/ColourboxDevelopment/simplesamlphp-module-redis/blob/master/config-templates/module_redis.php The file should be placed in the man config directory of the simpleSAMLphp installation.
